language: scala

scala:
  - 2.11.12

script:
  - sbt -Xms2048M -Xmx2048M -Xss6M -XX:MaxPermSize=512M clean coverage test coverageReport

after_success:
  - sbt -Xms2048M -Xmx2048M -Xss6M -XX:MaxPermSize=512M package
  - bash <(curl -s https://codecov.io/bash)
